data_preprocessing:
  min_overview_words: 15
  max_overview_words: 169
  top_cast: 10
  top_keywords: 10

paths:
  tmdb_download: "asaniczka/tmdb-movies-dataset-2023-930k-movies"
  lb_download: "https://huggingface.co/datasets/pkchwy/letterboxd-all-movie-data/resolve/main/full_dump.jsonl"
  tmdb_raw: "data/raw/TMDB_movie_dataset_v11.csv"
  lb_raw: "data/raw/full_dump.jsonl"
  film_data: "data/prep/film_data.csv"
  embeddings: "data/prep/embeddings_full_snowflake.npy"
  faiss_index: "indexes/index_FlatIP"
  faiss_metadata: "indexes/faiss_metadata.pkl"
  bm25_index: "indexes/bm25_meta"

models:
  embedding_model: "Snowflake/snowflake-arctic-embed-m"
  llm_repo: "bartowski/Llama-3.2-3B-Instruct-GGUF"
  llm_filename: "Llama-3.2-3B-Instruct-Q4_K_M.gguf"
  chat_format: "llama-3"

llm_params:
  n_ctx: 2048
  n_threads: 8
  temperature: 0.2
  max_tokens: 512